// <auto-generated />
using System;
using BloodConnect.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodConnect.Infrastructure.Migrations
{
    [DbContext(typeof(BloodConnectDbContext))]
    partial class BloodConnectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BloodConnect.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BloodConnect.Domain.BloodRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitsNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Urgency")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId");

                    b.ToTable("BloodRequests");
                });

            modelBuilder.Entity("BloodConnect.Domain.DonationHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DonationDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DonorProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FulfilledRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DonorProfileId");

                    b.ToTable("DonationHistoryEntries");
                });

            modelBuilder.Entity("BloodConnect.Domain.DonorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContactPreference")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasOptedIn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastDonationUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DonorProfiles");
                });

            modelBuilder.Entity("BloodConnect.Domain.DonorResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BloodRequestId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DonorUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProximityRank")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RespondedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DonorUserId");

                    b.HasIndex("BloodRequestId", "DonorUserId")
                        .IsUnique();

                    b.ToTable("DonorResponses");
                });

            modelBuilder.Entity("BloodConnect.Domain.NotificationOutboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdaptiveCardJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BloodRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryDetail")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReadByRecipient")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId");

                    b.ToTable("NotificationOutboxItems");
                });

            modelBuilder.Entity("BloodConnect.Domain.BloodRequest", b =>
                {
                    b.HasOne("BloodConnect.Domain.AppUser", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("BloodConnect.Domain.DonationHistoryEntry", b =>
                {
                    b.HasOne("BloodConnect.Domain.DonorProfile", "DonorProfile")
                        .WithMany("DonationHistory")
                        .HasForeignKey("DonorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonorProfile");
                });

            modelBuilder.Entity("BloodConnect.Domain.DonorProfile", b =>
                {
                    b.HasOne("BloodConnect.Domain.AppUser", "User")
                        .WithOne("DonorProfile")
                        .HasForeignKey("BloodConnect.Domain.DonorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodConnect.Domain.DonorResponse", b =>
                {
                    b.HasOne("BloodConnect.Domain.BloodRequest", "BloodRequest")
                        .WithMany("Responses")
                        .HasForeignKey("BloodRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodConnect.Domain.AppUser", "DonorUser")
                        .WithMany()
                        .HasForeignKey("DonorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloodRequest");

                    b.Navigation("DonorUser");
                });

            modelBuilder.Entity("BloodConnect.Domain.NotificationOutboxItem", b =>
                {
                    b.HasOne("BloodConnect.Domain.AppUser", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("BloodConnect.Domain.AppUser", b =>
                {
                    b.Navigation("DonorProfile");
                });

            modelBuilder.Entity("BloodConnect.Domain.BloodRequest", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("BloodConnect.Domain.DonorProfile", b =>
                {
                    b.Navigation("DonationHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
